export const BURGERBUILDER_TYPES = {
    
    RESET_INITIALIZEDVALUES: 'RESET_INITIALIZEDVALUES',

    INIT_INGREDIENTS: 'INIT_INGREDIENTS',
    INIT_INGREDIENTS_PRICE: 'INIT_INGREDIENTS_PRICE',
    INIT_BASE_PRICE: 'INIT_BASE_PRICE',

    UPDATE_INGREDIENTS: 'UPDATE_INGREDIENTS',
    UPDATE_PRICE: 'UPDATE_PRICE',

    SET_INGREDIENTS: 'SET_INGREDIENTS',
    SET_INGREDIENT_PRICE: 'SET_INGREDIENT_PRICE',
    SET_BASE_PRICE: 'SET_BASE_PRICE'
}

export const ORDER_TYPES = {

    PURCHASE_START: 'PURCHASE_START',
    FETCH_ORDERS_START: 'FETCH_ORDERS_START',

    LOAD_START: 'LOAD_START',
    LOAD_END: 'LOAD_END',
    PURCHASE_SUCCESS: 'PURCHASE_SUCCESS',
    PURCHASE_FAILURE: 'PURCHASE_FAILURE',
    RESET_PURCHASED: 'RESET_PURCHASED',

    FETCH_ORDERS_SUCCESS: 'FETCH_ORDERS_SUCCESS',
    FETCH_ORDERS_FAILURE: 'FETCH_ORDERS_FAILURE'
}

export const AUTH_TYPES = {
    AUTH_START: 'AUTH_START',
    AUTH_PROCESS: 'AUTH_PROCESS',
    AUTH_SUCCESS: 'AUTH_SUCCESS',
    AUTH_FAILURE: 'AUTH_FAILURE',
    AUTH_SIGNOUT_START: 'AUTH_SIGNOUT_START',
    AUTH_SIGNOUT: 'AUTH_SIGNOUT',
    AUTH_REDIRECT: 'AUTH_REDIRECT',
    AUTH_CHECK_TIMEOUT: 'AUTH_CHECK_TIMEOUT',
    AUTH_CHECK_STATE: 'AUTH_CHECK_STATE'
}

export const STATUS_TYPES = {
    ERROR: 'ERROR',
    SUCCESS: 'SUCCESS'
}